export const DASHBOARD_LOADED = "DASHBOARD_LOADED";
export const DASHBOARD_DESTROYED = "DASHBOARD_DESTROYED";
export const CARD_SELECTED = "CARD_SELECTED";
export const BALANCES_SCREEN_LOADED = "BALANCES_SCREEN_LOADED";
export const BALANCES_SCREEN_DESTROYED = "BALANCES_SCREEN_DESTROYED";
